import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRef, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [iframSrc, setIframeSrc] = useState("http://localhost:3001");
  const contentRef = useRef(null);
  const changeInnerPage = (path) => {
    setIframeSrc("http://localhost:3001" + path);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.sideBar}>
          <h3>Wake up neo...</h3>
          <div className={styles.menuContent}>
            <ul>
              <li>
                <button onClick={() => changeInnerPage("/contact")}>
                  Contact Page
                </button>
              </li>
              <li>
                <button onClick={() => changeInnerPage("/about-us")}>
                  About Us
                </button>
              </li>
              <li>
                <button onClick={() => changeInnerPage("/clients")}>
                  Clients Page
                </button>
              </li>
            </ul>
          </div>
        </div>

        <div className={styles.iframeContainer}>
          <iframe
            name="iaps"
            ref={contentRef}
            className={styles.iframeClass}
            height={"100%"}
            width={"100%"}
            src={iframSrc}
          ></iframe>
        </div>
      </main>
    </>
  );
}
